version: '3.8'
services:
  roleguard-bot:
    build: .
    container_name: roleguard_bot_prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./json/auto:/usr/src/app/json/auto
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"